"""
Start the FastAPI server, freeing the listen port if a stale process still holds it.

Usage (from project root):
    python scripts/run_api.py

Environment (optional, in .env or shell):
    API_HOST=127.0.0.1
    API_PORT=8000
"""

from __future__ import annotations

import os
import socket
import subprocess
import sys
import time
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent


def _load_dotenv_port() -> None:
    try:
        from dotenv import load_dotenv

        load_dotenv(PROJECT_ROOT / ".env")
    except ImportError:
        pass


def host() -> str:
    return os.getenv("API_HOST", "127.0.0.1").strip() or "127.0.0.1"


def port() -> int:
    return int(os.getenv("API_PORT", "8000"))


def is_port_in_use(bind_host: str, bind_port: int) -> bool:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        try:
            sock.bind((bind_host, bind_port))
            return False
        except OSError:
            return True


def pids_listening_on(bind_port: int) -> list[int]:
    pids: list[int] = []
    if sys.platform == "win32":
        result = subprocess.run(
            ["netstat", "-ano"],
            capture_output=True,
            text=True,
            errors="replace",
            check=False,
        )
        needle = f":{bind_port}"
        for line in result.stdout.splitlines():
            if "LISTENING" not in line or needle not in line:
                continue
            parts = line.split()
            if not parts:
                continue
            try:
                pid = int(parts[-1])
            except ValueError:
                continue
            if pid > 0:
                pids.append(pid)
    else:
        result = subprocess.run(
            ["lsof", "-ti", f":{bind_port}"],
            capture_output=True,
            text=True,
            check=False,
        )
        for token in result.stdout.split():
            try:
                pids.append(int(token))
            except ValueError:
                continue
    return list(dict.fromkeys(pids))


def stop_pids(pids: list[int]) -> None:
    for pid in pids:
        if sys.platform == "win32":
            subprocess.run(
                ["taskkill", "/F", "/PID", str(pid)],
                capture_output=True,
                check=False,
            )
        else:
            subprocess.run(["kill", "-9", str(pid)], capture_output=True, check=False)


def ensure_port_free(bind_host: str, bind_port: int) -> None:
    if not is_port_in_use(bind_host, bind_port):
        return

    pids = pids_listening_on(bind_port)
    if pids:
        print(
            f"Port {bind_port} is in use by PID(s): {', '.join(map(str, pids))}. "
            "Stopping stale process(es)..."
        )
        stop_pids(pids)
        time.sleep(1)

    if is_port_in_use(bind_host, bind_port):
        print(
            f"ERROR: Port {bind_port} is still in use.\n"
            f"  - Close the other app using this port, or\n"
            f"  - Set API_PORT to another value in .env (e.g. API_PORT=8001)\n"
            f"  - Update frontend/js/config.js to match the new port."
        )
        sys.exit(1)


def write_frontend_config(bind_host: str, bind_port: int) -> None:
    """Keep frontend API URL in sync when API_PORT is not the default."""
    if bind_port == 8000 and bind_host in ("127.0.0.1", "localhost"):
        return
    config_path = PROJECT_ROOT / "frontend" / "js" / "config.local.js"
    base = f"http://{bind_host}:{bind_port}"
    config_path.write_text(
        f'/** Auto-generated by scripts/run_api.py — do not edit unless needed */\n'
        f'export const API_BASE_URL = "{base}";\n',
        encoding="utf-8",
    )
    print(f"Wrote {config_path.relative_to(PROJECT_ROOT)} -> {base}")


def main() -> None:
    _load_dotenv_port()
    bind_host = host()
    bind_port = port()

    ensure_port_free(bind_host, bind_port)
    write_frontend_config(bind_host, bind_port)

    os.chdir(PROJECT_ROOT)
    url = f"http://{bind_host}:{bind_port}"
    print(f"Starting API at {url} (docs: {url}/docs)")
    cmd = [
        sys.executable,
        "-m",
        "uvicorn",
        "app.api.main:app",
        "--reload",
        "--host",
        bind_host,
        "--port",
        str(bind_port),
    ]
    raise SystemExit(subprocess.call(cmd))


if __name__ == "__main__":
    main()
